<?xml version="1.0"?>
<package format="3">
  <name>webui</name>
  <version>0.1.0</version>
  <description>Gradio-based web HMI node for experiment monitoring and control.</description>
  <maintainer email="lex.vyshnevskyy@gmail.com">Oleksii Vyshnevskyi</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>msgs</depend>
  <depend>core</depend>
  <depend>database</depend>

  <exec_depend>ament_index_python</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
