from __future__ import annotations

import ipaddress
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional

from .network_info import _run, collect_interfaces, get_interface, nmcli_available

# Personal hotspot (hardcoded per product spec).
HOTSPOT_SSID = 'NTNCND_DLT'
HOTSPOT_IP_CIDR = '172.16.0.2/24'
HOTSPOT_DHCP_START = '172.16.0.3'
HOTSPOT_DHCP_END = '172.16.0.12'
HOTSPOT_LEASE_TIME = '12h'
HOTSPOT_CONN_PREFIX = 'delatometry-hotspot-'

DELATOMETRY_ETC = Path('/etc/delatometry')
HOTSPOT_DNSMASQ_CONF = DELATOMETRY_ETC / 'hotspot-dnsmasq.conf'
HOTSPOT_STATE_FILE = Path('/run/delatometry/hotspot.interface')
HOTSPOT_DHCP_SERVICE = 'delatometry-hotspot-dnsmasq.service'


def _sudo(cmd: List[str], use_sudo: bool = True, timeout: float = 60.0) -> subprocess.CompletedProcess[str]:
    full = ['sudo', '-n', *cmd] if use_sudo else cmd
    return subprocess.run(full, capture_output=True, text=True, timeout=timeout, check=False)


def _connection_type(iface: str) -> str:
    info = get_interface(iface)
    if info and info.get('kind') == 'wifi':
        return 'wifi'
    return 'ethernet'


def _connections_on_interface(iface: str) -> List[str]:
    result = _run(['nmcli', '-t', '-f', 'NAME,DEVICE', 'con', 'show'])
    if result.returncode != 0:
        return []
    names: List[str] = []
    for line in result.stdout.splitlines():
        if ':' not in line:
            continue
        name, _, device = line.partition(':')
        if device.strip() == iface:
            names.append(name.strip())
    return names


def _delete_connections_on_interface(iface: str, use_sudo: bool = True) -> None:
    for name in _connections_on_interface(iface):
        if name:
            _sudo(['nmcli', 'connection', 'delete', name], use_sudo=use_sudo, timeout=30)


def _hotspot_connection_name(iface: str) -> str:
    return f'{HOTSPOT_CONN_PREFIX}{iface}'


def hotspot_is_active(iface: str = '') -> bool:
    try:
        active = HOTSPOT_STATE_FILE.read_text(encoding='utf-8').strip()
    except FileNotFoundError:
        active = ''
    if iface:
        return active == iface
    return bool(active)


def _write_hotspot_dnsmasq(iface: str) -> None:
    board = ipaddress.ip_interface(HOTSPOT_IP_CIDR)
    start = ipaddress.ip_address(HOTSPOT_DHCP_START)
    end = ipaddress.ip_address(HOTSPOT_DHCP_END)
    DELATOMETRY_ETC.mkdir(parents=True, exist_ok=True)
    HOTSPOT_STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    conf = f"""# Generated by Delatometry webui — personal hotspot
port=0
interface={iface}
bind-dynamic
dhcp-authoritative
dhcp-range={start},{end},{board.network.netmask},{HOTSPOT_LEASE_TIME}
dhcp-option=3,{board.ip}
dhcp-option=6,{board.ip}
"""
    HOTSPOT_DNSMASQ_CONF.write_text(conf, encoding='utf-8')
    HOTSPOT_STATE_FILE.write_text(iface + '\n', encoding='utf-8')


def _stop_hotspot_dnsmasq(use_sudo: bool = True) -> None:
    _sudo(['systemctl', 'disable', '--now', HOTSPOT_DHCP_SERVICE], use_sudo=use_sudo, timeout=30)
    for path in (HOTSPOT_DNSMASQ_CONF, HOTSPOT_STATE_FILE):
        try:
            path.unlink()
        except FileNotFoundError:
            pass


def enable_personal_hotspot(iface: str = 'wlan0', use_sudo: bool = True) -> Dict[str, Any]:
    if not nmcli_available():
        return {'ok': False, 'error': 'nmcli is not available'}
    iface = iface.strip()
    info = get_interface(iface)
    if not info:
        return {'ok': False, 'error': f'Interface {iface} not found'}
    if info.get('kind') != 'wifi':
        return {'ok': False, 'error': f'{iface} is not a Wi-Fi interface'}

    _stop_hotspot_dnsmasq(use_sudo)
    _delete_connections_on_interface(iface, use_sudo)

    conn = _hotspot_connection_name(iface)
    add = _sudo(
        [
            'nmcli', 'connection', 'add',
            'type', 'wifi',
            'ifname', iface,
            'con-name', conn,
            'ssid', HOTSPOT_SSID,
        ],
        use_sudo=use_sudo,
        timeout=30,
    )
    if add.returncode != 0:
        return {'ok': False, 'error': add.stderr.strip() or add.stdout.strip()}

    mod = _sudo(
        [
            'nmcli', 'connection', 'modify', conn,
            '802-11-wireless.mode', 'ap',
            'ipv4.addresses', HOTSPOT_IP_CIDR,
            'ipv4.method', 'manual',
            'ipv4.never-default', 'yes',
            'ipv6.method', 'ignore',
            'connection.autoconnect', 'yes',
        ],
        use_sudo=use_sudo,
        timeout=30,
    )
    if mod.returncode != 0:
        return {'ok': False, 'error': mod.stderr.strip() or mod.stdout.strip()}

    up = _sudo(['nmcli', 'connection', 'up', conn], use_sudo=use_sudo, timeout=45)
    if up.returncode != 0:
        return {'ok': False, 'error': up.stderr.strip() or up.stdout.strip()}

    try:
        _write_hotspot_dnsmasq(iface)
    except OSError as exc:
        return {'ok': False, 'error': f'Failed to write dnsmasq config: {exc}'}

    dhcp = _sudo(['systemctl', 'enable', '--now', HOTSPOT_DHCP_SERVICE], use_sudo=use_sudo, timeout=30)
    if dhcp.returncode != 0:
        return {
            'ok': False,
            'error': (
                f'Hotspot AP is up but DHCP failed: {dhcp.stderr.strip() or dhcp.stdout.strip()}. '
                'Install delatometry-hotspot-dnsmasq.service via install_services.sh'
            ),
        }
    return {
        'ok': True,
        'error': '',
        'message': (
            f'Hotspot {HOTSPOT_SSID!r} on {iface}: {HOTSPOT_IP_CIDR}, '
            f'clients {HOTSPOT_DHCP_START}–{HOTSPOT_DHCP_END} (open, no password)'
        ),
    }


def disable_personal_hotspot(use_sudo: bool = True) -> Dict[str, Any]:
    iface = ''
    try:
        iface = HOTSPOT_STATE_FILE.read_text(encoding='utf-8').strip()
    except FileNotFoundError:
        pass
    _stop_hotspot_dnsmasq(use_sudo)
    if iface:
        conn = _hotspot_connection_name(iface)
        _sudo(['nmcli', 'connection', 'down', conn], use_sudo=use_sudo, timeout=20)
        _sudo(['nmcli', 'connection', 'delete', conn], use_sudo=use_sudo, timeout=20)
    return {'ok': True, 'error': '', 'message': 'Hotspot disabled'}


def set_interface_admin_state(iface: str, up: bool, use_sudo: bool = True) -> Dict[str, Any]:
    if not nmcli_available():
        return {'ok': False, 'error': 'nmcli is not available'}
    iface = iface.strip()
    if hotspot_is_active(iface) and not up:
        return {'ok': False, 'error': 'Disable hotspot before taking interface down'}
    action = 'connect' if up else 'disconnect'
    proc = _sudo(['nmcli', 'device', action, iface], use_sudo=use_sudo, timeout=30)
    ok = proc.returncode == 0
    return {
        'ok': ok,
        'error': '' if ok else (proc.stderr.strip() or proc.stdout.strip() or f'failed to {action}'),
    }


def configure_interface_dhcp(iface: str, use_sudo: bool = True) -> Dict[str, Any]:
    if not nmcli_available():
        return {'ok': False, 'error': 'nmcli is not available'}
    iface = iface.strip()
    if hotspot_is_active(iface):
        return {'ok': False, 'error': 'Disable hotspot on this interface first'}

    _delete_connections_on_interface(iface, use_sudo)
    conn_type = _connection_type(iface)
    conn_name = f'{iface}-dhcp'
    add = _sudo(
        [
            'nmcli', 'connection', 'add',
            'type', conn_type,
            'ifname', iface,
            'con-name', conn_name,
            'ipv4.method', 'auto',
            'ipv6.method', 'ignore',
            'connection.autoconnect', 'yes',
        ],
        use_sudo=use_sudo,
        timeout=30,
    )
    if add.returncode != 0:
        return {'ok': False, 'error': add.stderr.strip() or add.stdout.strip()}
    up = _sudo(['nmcli', 'connection', 'up', conn_name], use_sudo=use_sudo, timeout=45)
    ok = up.returncode == 0
    return {
        'ok': ok,
        'error': '' if ok else (up.stderr.strip() or up.stdout.strip()),
        'message': f'{iface} set to DHCP',
    }


def configure_interface_static(
    iface: str,
    address: str,
    prefix: int,
    gateway: str = '',
    dns: str = '',
    use_sudo: bool = True,
) -> Dict[str, Any]:
    if not nmcli_available():
        return {'ok': False, 'error': 'nmcli is not available'}
    iface = iface.strip()
    if hotspot_is_active(iface):
        return {'ok': False, 'error': 'Disable hotspot on this interface first'}
    address = address.strip()
    if not address:
        return {'ok': False, 'error': 'IPv4 address is required'}

    cidr = f'{address}/{int(prefix)}'
    _delete_connections_on_interface(iface, use_sudo)
    conn_type = _connection_type(iface)
    conn_name = f'{iface}-static'
    cmd = [
        'nmcli', 'connection', 'add',
        'type', conn_type,
        'ifname', iface,
        'con-name', conn_name,
        'ipv4.addresses', cidr,
        'ipv4.method', 'manual',
        'ipv6.method', 'ignore',
        'connection.autoconnect', 'yes',
    ]
    if gateway.strip():
        cmd.extend(['ipv4.gateway', gateway.strip()])
    if dns.strip():
        cmd.extend(['ipv4.dns', dns.strip()])
    add = _sudo(cmd, use_sudo=use_sudo, timeout=30)
    if add.returncode != 0:
        return {'ok': False, 'error': add.stderr.strip() or add.stdout.strip()}
    up = _sudo(['nmcli', 'connection', 'up', conn_name], use_sudo=use_sudo, timeout=45)
    ok = up.returncode == 0
    return {
        'ok': ok,
        'error': '' if ok else (up.stderr.strip() or up.stdout.strip()),
        'message': f'{iface} static IPv4 {cidr}',
    }


def wifi_scan(iface: str = 'wlan0') -> Dict[str, Any]:
    if not nmcli_available():
        return {'ok': False, 'error': 'nmcli is not available', 'rows': []}
    if hotspot_is_active(iface):
        return {'ok': False, 'error': 'Disable hotspot before Wi-Fi client scan', 'rows': []}
    _sudo(['nmcli', 'device', 'wifi', 'rescan', 'ifname', iface], use_sudo=True, timeout=20)
    result = _run(['nmcli', '-t', '-f', 'IN-USE,SSID,SIGNAL,SECURITY', 'dev', 'wifi', 'list', 'ifname', iface])
    if result.returncode != 0:
        return {'ok': False, 'error': result.stderr.strip() or result.stdout.strip(), 'rows': []}
    rows: List[List[Any]] = []
    for line in result.stdout.splitlines():
        parts = line.split(':')
        if len(parts) < 4:
            continue
        rows.append([parts[0], parts[1], parts[2], parts[3]])
    return {'ok': True, 'error': '', 'rows': rows}


def wifi_connect(ssid: str, password: str, interface: str = 'wlan0', use_sudo: bool = True) -> Dict[str, Any]:
    if not nmcli_available():
        return {'ok': False, 'error': 'nmcli is not available'}
    if hotspot_is_active(interface):
        return {'ok': False, 'error': 'Disable hotspot before connecting as Wi-Fi client'}
    ssid = ssid.strip()
    if not ssid:
        return {'ok': False, 'error': 'SSID is required'}
    cmd = ['nmcli', 'dev', 'wifi', 'connect', ssid, 'ifname', interface]
    if password.strip():
        cmd.extend(['password', password.strip()])
    proc = _sudo(cmd, use_sudo=use_sudo, timeout=60)
    return {
        'ok': proc.returncode == 0,
        'error': '' if proc.returncode == 0 else (proc.stderr.strip() or proc.stdout.strip()),
    }


# Backward-compatible wrappers (connection profile name == interface-bound con)
def set_ipv4(connection: str, address: str, prefix: int, gateway: str = '', dns: str = '', use_sudo: bool = True) -> Dict[str, Any]:
    return configure_interface_static(connection, address, prefix, gateway, dns, use_sudo)


def set_dhcp(connection: str, use_sudo: bool = True) -> Dict[str, Any]:
    return configure_interface_dhcp(connection, use_sudo)
